routes:
    home:           'Default:home'
    convert:        'Default:convert'
    pin:            'Default:pin'
    crush:          'Default:crush'
    deleteList:     'Default:deleteList'
    deleteFavorite: 'Default:deleteFavorite'
    basket:         'Default:basket'
    recipe:         'Default:recipe'
    filterRecipe:   'Default:filterRecipe'
    about:          'Default:about'
    contact:        'Default:contact'
    profile:        'Default:profile'    
    login:          'Security:login'
    logout:         'Security:logout'
    register:       'Security:register'
    editProfile:    'Security:editProfile'

defaut_route: 'home'

db_config:
    name: 'projet_transversal'
    host: 'localhost'
    user: 'root'
    pass: ''
