routes:
    home:           'Default:home'
    convert:        'Default:convert'
    basket:         'Default:basket'
    recipe:         'Default:recipe'
    about:          'Default:about'
    contact:        'Default:contact'
    login:          'Security:login'
    logout:         'Security:logout'
    register:       'Security:register'
    profile:        'Security:profile'        
    editProfile:    'Security:editProfile'
    pin:            'Security:pin'
    crush:          'Security:crush'
    deleteList:     'Security:deleteList'
    deleteFavorite: 'Security:deleteFavorite'
    deleteProfile:  'Security:deleteProfile'
    admin:          'Admin:admin'
    deleteUser:     'Admin:deleteUser'
    addAdmin:       'Admin:addAdmin'
    addRecipe:      'Admin:addRecipe'
    addBasket:      'Admin:addBasket'
    addIngredient:  'Admin:addIngredient'
    deleteBasket:   'Admin:deleteBasket'
    deleteRecipe:   'Admin:deleteRecipe'
    deleteIngredient: 'Admin:deleteIngredient'

defaut_route: 'home'

db_config:
    name: 'projet_transversal'
    host: 'localhost'
    user: 'root'
    pass: ''
