routes:
    home:           'Default:home'
    convert:        'Default:convert'
    pin:            'Default:pin'
    basket:         'Default:basket'
    recipe:         'Default:recipe'
    filterRecipe:   'Default:filterRecipe'
    about:          'Default:about'
    contact:        'Default:contact'
    login:          'Security:login'
    logout:         'Security:logout'
    register:       'Security:register'
    profile:        'Security:profile'
    editProfile:    'Security:editProfile'

defaut_route: 'home'

db_config:
    name: 'projet_transversal'
    host: 'localhost'
    user: 'root'
    pass: ''
